#!/bin/sh
# Author: Jens Getreu

# set -x

render () {

SCRIPT_DIR=$(dirname $(readlink -f $0))
AdocBase=$(basename "$1" ".adoc")
cd "source" || echo "Error: no source directory found!" || exit 1
InDir="./"
OutDir="../build/pdf"
mkdir -p "$OutDir"
PdfBase=$(basename "$2" ".pdf")
XmlFile="$OutDir/$AdocBase.xml"
PdfFile="$OutDir/$PdfBase.pdf"

asciidoctor -b docbook -a data-uri!  -D "$OutDir" "$1"

cp -r "$InDir/images/" "$OutDir"
cp -r "$InDir/docbook-xsl" "$OutDir"

"$SCRIPT_DIR/docbook52pdf" "$XmlFile" "$PdfFile"

rm -R "$OutDir/images"
rm -R "$OutDir/docbook-xsl"
rm "$XmlFile"

}


render "index.adoc" "legacy-to-uefi-boot.pdf" \
