
= Switch Debian from legacy to UEFI boot mode
//26.10.2014
//30.1.2017
//11.3.2017
07.08.2019
Jens Getreu
:icons: font
:data-uri:
//:stem: latexmath
:numbered:
:toc:
:pagenums:
:experimental:

// excerpt-begin

This note explains how to switch a legacy boot Debian/Ubuntu system into a 
UEFI boot system. Typical use case: 

- switch a legacy boot installation into an UEFI one,
- reinstall a broken UEFI boot loader on Debian 7, Debian 8, Debian 9 or Debian 10.

// excerpt-end

NOTE: This manual has been tested on Debian 7 Wheezy, Debian 8 Jessie, 
Debian 9 Stretch and Debian 10 Buster. 


== Boot a live system

. Enable UEFI in bios.

. Boot an https://www.debian.org/CD/live/[recent Debian live]
  system on USB or DVD.



== Prepare the harddisk

=== Back up your data

Back up your data!



=== Identify Debian's "`/boot`" partition

My lecagy boot system had a 243MiB 
ext2 partition mounted on /boot. This partition is never encrypted. 
It is where the grub files and Linux 
kernels reside. Check by double clicking on the 
partition icon on the live-disk-desktop and have a look inside. 


  
[subs="+quotes"]
....
# _ls -l_
total 21399
-rw-r--r-- 1 root root   155429 Sep 28 00:59 config-3.16-0.bpo.2-amd64
drwxr-xr-x 3 root root     7168 Nov  5 08:03 grub
-rw-r--r-- 1 root root 15946275 Nov  5 16:28 initrd.img-3.16-0.bpo.2-amd64
drwx------ 2 root root    12288 Nov 24  2012 lost+found
-rw-r--r-- 1 root root  2664392 Sep 28 00:59 System.map-3.16-0.bpo.2-amd64
-rw-r--r-- 1 root root  3126096 Sep 28 00:48 vmlinuz-3.16-0.bpo.2-amd64
....

[subs="+quotes"]
....
# _df -h_
Filesystem             Size  Used Avail Use% Mounted on
...
/dev/sdb1              234M   28M  206M  13% /media/....
....

As you can see in the following partition table of the Debian legacy 
boot system my `/boot` partition is number 1 
(`/dev/sdb1`).

WARNING: Although 1 is the default value 
for standard debian installations better check!

NOTE: The live system has identified this partition as 
`/dev/sdb`. The debian system on your harddisk could reference it 
differently.


.Partition table of the Debian legacy boot system

[subs="+quotes"]
----
# _fdisk -l /dev/sdb_
...
   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1   ***        2048      499711       44032    7  HPFS/NTFS/exFAT
...
/dev/sdb5          501760   976771071   488134656   83  Linux
----

In legacy boot mode the `/boot` partition must have the `boot`-flag (*) set.
This confirms our assumption: the `/boot` filesystem is on: `/dev/sdb1`.

[subs="+quotes"]
----
# _gdisk -l /dev/sdb_
GPT fdisk (gdisk) version 0.8.5

Partition table scan:
  *MBR: MBR only*
  BSD: not present
  APM: not present
  GPT: not present
...
Number  Start (sector)    End (sector)  Size       Code  Name
   *1*            2048          499711   *243.0 MiB   8300  Linux filesystem*
   5          501760       976771071   238.2 GiB   8300  Linux filesystem
----



=== Create GPT partition table

Transform the partition table from MBR to GPT with 

[subs="+quotes"]
....
  #_gdisk /dev/sdb_
  
  _r_       recovery and transformation options (experts only)
  _f_       load MBR and build fresh GPT from it
....




=== Create an UEFI partition

A good graphical tool is the Gnome Partition Editor `gparted`:

[subs="+quotes"]
  # _gparted /dev/sdb_

. Shrink the `/boot` partition to 200MB in order to free 43MB (see 
  partition 1 below).

. Create a new 43MB partition for efi using `gparted` with partition 
  code `EF00` (EFI system) and flag it *bootable*. Format the partition 
  with a _fat32_ footnote:[fat32=vfat in `/etc/fstab`] filesystem (see 
  partition 2 below).

. UEFI needs additionally   
  footnote:[I have not verified if the additional 1MB partition is 
  really necessary. Omitting this step the following error message may 
  occur: `GPT detected. Please create a BIOS-Boot partition (>1MB, 
  unformatted filesystem, bios_grub flag). This can be performed via 
  tools such as Gparted. Then try again.`]  a _not_ formatted 1MB 
  partition . footnote:[Some say it should have the flag *bios_grub*, 
  for me it works without.] (see partition 3 below).




Leave the other partitions untouched (see partition 5 
below).


Here the result:

.Partition table of the Debian UEFI boot system
[subs="+quotes"]
....
# _gdisk -l /dev/sdb_
GPT fdisk (gdisk) version 0.8.5

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  *GPT: present*

*Found valid GPT* with protective MBR; *using GPT*.
Disk /dev/sdb: 976773168 sectors, 465.8 GiB

...

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          411647   200.0 MiB   8300  Linux filesystem
   2          411648          499711  *43.0 MiB    EF00  Efi partition*
   3          499712          501759  *1024.0 KiB  8300  Linux filesystem*
   5          501760       976771071   465.5 GiB   8300  Linux filesystem
....
footnote:[I noticed on my system the code EF00 
changed somehow to 0700. Why?]


== Mount the Debian filesystem

The next step differs whether the `root`-filesystem is encrypted or not.


=== Mount a non-encrypted `root`-filesystem

. Mount the `/` (root) filesystem. 
+
* For non-encrypted root filesystems a simple `mount` will do.
+
[subs="+quotes"]
  _# mount -t ext4 /dev/sdb5 /mnt_


=== Mount an encrypted `root`-filesystem

* For encrypted root filesystems the mounting procedure can be a little 
tricky especially when the root filesystem resides inside a logical 
volume which is encrypted. This section shows how to mount and 
unmount an encrypted `root`-filesystem.  



NOTE: The recovery mode of the Debian 9 Stretch installer disk
automates all following steps. Try this first. If it does not work 
follow the rest of this section.

==== Find the device and partition of the to be mounted logical volume

. Connect the disk with `host-system` and observe the kernel messages in `/var/log/syslog`
+
[subs="+quotes"]
....
 root@host-system:~# _tail -f /var/log/syslog_
 sd 3:0:0:0: [sdb] 976773168 512-byte logical blocks: (500 GB/465 GiB)
 sd 3:0:0:0: [sdb] Write Protect is of manually.
 sd 3:0:0:0: [sdb] Mode Sense: 43 00 00 00
 sd 3:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
  sdb: sdb1 sdb2 sdb3 sdb5
 sd 3:0:0:0: *[sdb] Attached SCSI disk*
....
+
The to be mounted device is `/dev/sdb`.

. Find the partition
+
[subs="+quotes"]
....
root@host-system:~# _gdisk -l /dev/sdb_
GPT fdisk (gdisk) version 0.8.5
...
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          411647   200.0 MiB   8300  Linux filesystem
   2          411648          494821   43.0 MiB    0700  
   3          494822          501759   1024.0 KiB  8300  Linux filesystem
   *5*          501760       976771071   465.5 GiB   8300  Linux filesystem
....
+
*The to be mounted logical volume of `disk-system` resides on `/dev/sdb5`.* 
//The filssystems of `host-system` are on `/dev/sdb`.

////
. Make sure that `/dev/sdb5` is not mounted yet.
+
[subs="+quotes"]
 # _mount_
+
`/dev/sdb5` should not be listed in the output of `mount`.
////



==== Mount encrypted logical volume 

. Open decryption layer.
+
--
[subs="+quotes"]
....
root@host-system:~# _lvscan_
  ACTIVE            '/dev/host-system/root' [231.03 GiB] inherit
  ACTIVE            '/dev/host-system/swap_1' [7.20 GiB] inherit
....
Logical volume is not registered yet. Do so.

[subs="+quotes"]
....
root@host-system:~# _cryptsetup luksOpen */dev/sdb5* **sdb5**_crypt_
Enter passphrase for /dev/sdb5: 
....

Enter disk password.

[subs="+quotes"]
....
root@host-system:~# _lvscan_
  *inactive          '/dev/disk-system/root' [457.74 GiB] inherit*
  *inactive          '/dev/disk-system/swap_1' [7.78 GiB] inherit*
  ACTIVE            '/dev/host-system/root' [231.03 GiB] inherit
  ACTIVE            '/dev/host-system/swap_1' [7.20 GiB] inherit
....

Logical volume of `disk-system`is registered now. It contains one `root` 
partition (line 1) and and one `swap` partition (line 2).

--

. Activate logical volumes
+
--
[subs="+quotes"]
  root@host-system:~# _lvchange -a y disk-system_

Check success.

[subs="+quotes"]
....
root@host-system:~# _lvscan_
  *ACTIVE*            '/dev/disk-system/root' [457.74 GiB] inherit
  *ACTIVE*            '/dev/disk-system/swap_1' [7.78 GiB] inherit
  ACTIVE            '/dev/host-system/root' [231.03 GiB] inherit
  ACTIVE            '/dev/host-system/swap_1' [7.20 GiB] inherit

root@host-system:~# ls /dev/mapper
control  *disksystem-root*  disksystem-swap_1  hostsystem-root  hostsystem-swap_1  mymapper  sdb5_crypt
....
--

. Mount logical volume
+
--
[subs="+quotes"]
 root@host-system:~# _mount -t ext4 /dev/mapper/disksystem-root /mnt_

Check success.

[subs="+quotes"]
....
root@host-system:~# _ls /mnt_
bin   etc         initrd.img.old  lib64       mnt   proc  sbin     sys  var
boot  home        lib             lost+found  mnt2  root  selinux  tmp  vmlinuz
dev   initrd.img  lib32           media       opt   run   srv      usr  vmlinuz.old
....
--




==== Unmount encrypted logical volume

This subsection is only for completeness. Skip it.

[subs="+quotes"]
....
root@host-system:~# _umount /mnt_

root@host-system:~# _lvscan_
  ACTIVE            '/dev/disk-system/root' [457.74 GiB] inherit
  ACTIVE            '/dev/disk-system/swap_1' [7.78 GiB] inherit
  ACTIVE            '/dev/host-system/root' [231.03 GiB] inherit
  ACTIVE            '/dev/host-system/swap_1' [7.20 GiB] inherit

root@host-system:~# _lvchange -a n disk-system_
root@host-system:~# _lvscan_
  *inactive*          '/dev/disk-system/root' [457.74 GiB] inherit
  *inactive*          '/dev/disk-system/swap_1' [7.78 GiB] inherit
  ACTIVE            '/dev/host-system/root' [231.03 GiB] inherit
  ACTIVE            '/dev/host-system/swap_1' [7.20 GiB] inherit

root@host-system:~# _cryptsetup luksClose sdb5_crypt_
root@host-system:~# _lvscan_
  ACTIVE            '/dev/host-system/root' [231.03 GiB] inherit
  ACTIVE            '/dev/host-system/swap_1' [7.20 GiB] inherit
....




=== Mount the remaining filesystems

Either this way...

[subs="+quotes"]
  _# mount /dev/sdb1 /mnt/boot
  # mount /dev/sdb2 /mnt/boot/efi
  # for i in /dev/ /dev/pts /proc /sys ; do mount -B $i /mnt/$i ; done_

or this way, both commands do the same...

[subs="+quotes"]
  _# mount /dev/sdb1 /mnt/boot
  # mount /dev/sdb2 /mnt/boot/efi
  # mount --bind /sys /mnt/sys
  # mount --bind /proc /mnt/proc
  # mount --bind /dev /mnt/dev
  # mount --bind /dev/pts /mnt/dev/pts_


.Internet access 

For internet access inside chroot:

[subs="+quotes"]
  _# cp /etc/resolv.conf /mnt/etc/resolv.conf_  


== Update debians /etc/fstab

Update the entries in `/mnt/etc/fstab` to reflect the partition changes
above. Compare the UUID's there with the ones listed here:
 
[subs="+quotes"]
   # _ls /dev/disk/by-uuid_

Add the new UEFI partition (see last line in `/etc/fstab` below) in 
order to get it mounted permanently on `/boot/efi`.

[subs="+quotes"]
....
# _cat /mnt/etc/fstab_
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/koobue1-root /      ext4    errors=remount-ro 0       1
# /boot was on /dev/sdb1 during installation
*UUID=040cdd12-8e45-48bd-822e-7b73ef9fa09f  /boot   ext2*  defaults 0  2
/dev/mapper/koobue1-swap_1 none swap    sw              0       0
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0
#Jens: tmpfs added for SSD
tmpfs           /tmp            tmpfs   defaults,nodev,nosuid,size=500m 0 0 
tmpfs           /var/lock       tmpfs   defaults,nodev,nosuid,noexec,mode=1777,size=100m 0 0 
tmpfs           /var/run        tmpfs   defaults,nodev,nosuid,noexec,mode=0775,size=100m 0 0 
*UUID=19F0-4372  /boot/efi       vfat*    defaults        0       2
....

TIP: I use `/dev/mapper` for the encrypted file system and `tmpfs` 
because I have an SSD disk. 


== Inside the `chroot` environment 

=== Preparation

Enter with:

[subs="+quotes"]
  # _chroot /mnt_
  

Check

[subs="+quotes"]
  # _cat /etc/fstab_
  
for not yet mounted entries and mount them manually e.g.

[subs="+quotes"]
  # _mount /tmp
  # mount /run
  # mount /var/lock_
  ...
  

  
=== Install grub-efi

[subs="+quotes"]
  # _apt-get remove grub-pc
  # apt-get install grub-efi_

[subs="+quotes"]
  # _grub-install /dev/sdb_

Check presence of the efi file:

[subs="+quotes"]
  # _file /boot/efi/EFI/debian/grubx64.efi_
  /boot/efi/EFI/debian/grubx64.efi: PE32+ executable (EFI application) x86-64 (stripped to external PDB), for MS Windows

A Debian entry should be listed here:

[subs="+quotes"]
....
# _efibootmgr_ 
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,2001,2002,2003
Boot0000* *debian*
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
....
 
Exit chroot environment.
  
[subs="+quotes"]
  _exit_

Reboot the system.


== Validate the debian bootloader in UEFI Bios

The bios will not accept the bootloader by default, because
`/EFI/debian/grubx64.efi` is not the default path and 
because the file has no Microsoft signature. 

This is why `grubx64.efi` has to be validated manually 
in the UEFI bios setup. In my InsydeH20 Bios I selected:

menu:Security[Select an UEFI file as trusted > Enter]

Then browse to
 
  /EFI/debian/grubx64.efi

in order to insert the grub boot loader in the trusted bootloader bios database.

NOTE: On my Acer E3-111 the bios menu entry was disabled by default.
      To enable it I had to define first a supervisor password. +
menu:Security[Set Supervisor Password > Enter]


== References

Tanguy:: Tanguy: _Debian: switch to UEFI boot._ 
http://tanguy.ortolo.eu/blog/article51/debian-efi. April 2012. 

Vulcan:: Vulcan, Silviu: _Linux on the Acer E3-111 – Aspire 
E3-111-C5FN_. 
http://www.sgvulcan.com/linux-on-the-acer-e3-111-aspire-e3-111-c5fn/ . 
09/2014. 
